name: Build and Package

on:
  push:
    branches: 
      - 4.1
  pull_request:
    branches: 
      - 4.1
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  VERSION: 'beta 4.1'

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-latest
    environment: Auto Build And Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Set env
        run: |
          sT=$(TZ=UTC-8 date +'%S')
          echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
          echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}
          echo ${{ env.logT }}

      - name: Pre body
        run: |
          echo -e "更新时间：${{ env.logT }}" >> release.txt
          echo -e "> - 同步官方beta 4.1代码更新，个别汉化等我修复" >> release.txt
          sed -i '' "s/AAA/版本：${{ env.VERSION }}/g" ./Bootstrap/Views/ContentView.swift
          sed -i '' "s/AAB/${{ env.msT }}/g" ./Bootstrap/Views/ContentView.swift
      
      - name: Build Bootstrap
        run: |
          make package
          mv ./packages/Bootstrap.tipa Bootstrap.ipa

      - name: Release ipa
        uses: softprops/action-gh-release@v1
        with:
          name: Bootstrap_${{ env.VERSION }}
          tag_name: ${{ env.msT }}
          target_commitish: 3.1
          body_path: release.txt
          latest: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.ipa
